<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text23_text23</name>
   <tag></tag>
   <elementGuidId>f287628c-240f-4186-9208-ac1c80a3f927</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d88cd15-8005-4d01-9de5-855b58189047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab6f0aa8-0826-4c2a-b5a3-e2a4aee42223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text23</value>
      <webElementGuid>512fbd0d-44ab-498f-9ae1-edba5e0084d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text23&quot;)</value>
      <webElementGuid>ead55bd1-64cf-4568-998e-24bf6d363521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text23']</value>
      <webElementGuid>fb701e4e-5897-4338-86ff-01d92745a6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[23]</value>
      <webElementGuid>896e4365-063d-475f-8314-961f1f79f87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text23']</value>
      <webElementGuid>55056220-23e2-4c30-b47c-2ae330235ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
