<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text36_text36</name>
   <tag></tag>
   <elementGuidId>16ff1baa-e498-49fd-9a28-f03d72bfb1a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text36']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcb3efc2-6b50-40e4-aea5-29b36a810463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3a685e2-bc7d-405c-bf1e-2d759bd551bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text36</value>
      <webElementGuid>fb84fff5-4020-44db-9453-a610df876e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text36&quot;)</value>
      <webElementGuid>c1c02803-6c3e-4be8-9570-0adc1f72737d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text36']</value>
      <webElementGuid>820c77e3-0e06-4051-aebd-a4ba94f7a137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[36]</value>
      <webElementGuid>c4963a71-fa22-49eb-a7c8-ca906e47a2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text36']</value>
      <webElementGuid>14d2b610-6b6c-415d-84fe-f4443228e9bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
