<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text6_text6</name>
   <tag></tag>
   <elementGuidId>67b486d6-59f7-4aa0-8f63-01b7786c7b62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59c1ee9e-e7f0-401d-ac28-908c97d72d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdcc6f51-121d-4b26-91a3-25a63bc403ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text6</value>
      <webElementGuid>15608c90-69b2-4c1f-95f6-51216d8725b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text6&quot;)</value>
      <webElementGuid>2fae4d73-a512-417b-a8af-8cb3a1a9a56c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text6']</value>
      <webElementGuid>52ff46ab-3536-417d-823b-e1d331c3950d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>52c41b15-6200-423b-a611-8b2ff8869e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text6']</value>
      <webElementGuid>7298e703-07a6-4280-81a8-664f5900fb33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
