<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text28_text28</name>
   <tag></tag>
   <elementGuidId>1827f6ee-15dc-4d49-94ed-37db01fd4283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text28</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text28']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d462b8b9-8bac-4b83-b73a-d64b46bf44fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d2b4ded-b601-40b9-99a9-e3b93133e93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text28</value>
      <webElementGuid>cac63bb5-e724-4571-872e-4c9424efd369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text28&quot;)</value>
      <webElementGuid>8dc34147-3436-4d13-bcc6-f6aed3304fc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text28']</value>
      <webElementGuid>75a9f6c4-7916-42d9-afa3-533482e549c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[28]</value>
      <webElementGuid>eb3b60fd-a278-4e6b-b97e-200ae385528b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text28']</value>
      <webElementGuid>89605d28-8e81-41e8-b521-88629ae732e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
