<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text27_text27</name>
   <tag></tag>
   <elementGuidId>9fed6db0-59b3-40ca-876e-18580e927f42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text27']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da88c0a8-7bdd-4de9-bf78-5deea5e2b94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>023b6c6a-6a96-4cde-a515-1c0d43627ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text27</value>
      <webElementGuid>6cc7cb0a-296e-40f8-bf44-3bf24e084a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text27&quot;)</value>
      <webElementGuid>777580da-ab54-42b4-ac05-f32d3b0b58cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text27']</value>
      <webElementGuid>04026f1e-df69-4869-987e-132776882608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[27]</value>
      <webElementGuid>3dbbaf86-587b-4114-8e2e-8e1975c1601d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text27']</value>
      <webElementGuid>996a58b5-e69b-4ed6-aa68-d904781c469a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
