<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text29_text29</name>
   <tag></tag>
   <elementGuidId>fb480000-903b-48ff-af0b-b4a50545b949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text29</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d763d0d5-1c11-45af-89e1-c20c4dec0d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c34aeaad-7777-4dde-bfce-9a6a7545eb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text29</value>
      <webElementGuid>7cefece9-8e74-4734-aa37-1c18dd5e6e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text29&quot;)</value>
      <webElementGuid>a36f031c-e8e2-49e4-9e4d-c81fb020a8e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text29']</value>
      <webElementGuid>fe8a8d01-3686-4af5-b954-d09c0afa5ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[29]</value>
      <webElementGuid>566c8772-4c53-4356-ab53-f6ba3a558b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text29']</value>
      <webElementGuid>98df8411-bd9f-4392-87c0-ec0d3b6266aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
