<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text33_text33</name>
   <tag></tag>
   <elementGuidId>13403ec8-d699-4218-90be-e758e30ffb9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text33']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fa233a9-5ec9-4620-a75e-78e8f467a3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7fad37b-5421-4b94-b33a-5bb084473865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text33</value>
      <webElementGuid>d67f4b87-4b96-4917-9927-ef6291cc4d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text33&quot;)</value>
      <webElementGuid>8886dda2-3296-4b4f-a07f-a660bd1f8594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text33']</value>
      <webElementGuid>a80c0ac5-887e-458c-8179-f289ff612e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[33]</value>
      <webElementGuid>df5512f5-eb05-421f-91d6-959bbff7ba6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text33']</value>
      <webElementGuid>9e174816-5344-4b67-8da3-b76d2c6e20b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
