<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text16_text16</name>
   <tag></tag>
   <elementGuidId>f7675849-89f3-40ff-aa29-11ef72d60746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f46efd9-e0fb-4214-87af-90e6520b0d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e45495d8-314b-4d0a-bc98-28aa99a671ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text16</value>
      <webElementGuid>72457aee-e5b8-4c3f-b41a-f9a87f9ee2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text16&quot;)</value>
      <webElementGuid>efd92e45-3cd8-4d8f-b0cd-fd45a3609bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text16']</value>
      <webElementGuid>3dd6eef8-e244-4d55-b1be-6a5c28afa382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[16]</value>
      <webElementGuid>79186bd4-d418-4845-a9b0-303867b2bf12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text16']</value>
      <webElementGuid>075e4cb5-4f23-4fb9-aeab-bd8418bd3612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
