<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text32_text32</name>
   <tag></tag>
   <elementGuidId>d7cdf481-e426-454c-86ed-f53ad3a4da52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text32</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text32']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dd5f972-b472-48ea-b20e-2d75e456cb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61f27ccd-7827-4c58-9b71-ea8021db99ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text32</value>
      <webElementGuid>0430d2a9-5f0b-48c2-8148-7f856715c470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text32&quot;)</value>
      <webElementGuid>1d57416f-4917-4184-bbd4-8cc10b667d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text32']</value>
      <webElementGuid>dfbbfe7e-2e99-4c49-ac67-3cc5e3280801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[32]</value>
      <webElementGuid>4bc4869f-b560-4c1d-9fa2-c283f7724ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text32']</value>
      <webElementGuid>f6be8a35-ceb5-4af7-a90b-6ab1bb38cd31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
