<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text9_text9</name>
   <tag></tag>
   <elementGuidId>ae58aef7-1f72-4098-b38c-de9eb9eab6c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>911e70ae-cc29-4bce-9d3d-5a0871357b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a7d6a46-fd41-4b26-95bb-b0f08f33ce1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text9</value>
      <webElementGuid>9b3f692c-2325-4baf-89db-be9412ba25f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text9&quot;)</value>
      <webElementGuid>70fe6ecc-4e88-4aa6-b896-a532ab9d9bfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text9']</value>
      <webElementGuid>ab5b4221-f0ab-4f5b-aa89-d3e364582bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[9]</value>
      <webElementGuid>615e453e-c214-4b8b-a132-538c7e4cc23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text9']</value>
      <webElementGuid>9045fc5b-1ecf-4594-8570-a45f665dfa7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
