<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text24_text24</name>
   <tag></tag>
   <elementGuidId>c8d91f56-9801-4a56-a447-ab3cb334e0e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text24</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text24']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd088de6-ff53-47ab-8623-4b64cefbbe12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>73219f13-723b-4616-b5d9-b14f762a4056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text24</value>
      <webElementGuid>beb83b0d-75e6-463c-ba34-39fe2ca05e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text24&quot;)</value>
      <webElementGuid>24679671-b52a-4e9a-ad6d-be9c0c168869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text24']</value>
      <webElementGuid>9d64d928-46d1-47f9-af0b-1507e76b5ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[24]</value>
      <webElementGuid>7e391729-3cc9-40e4-8506-aef13086caec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text24']</value>
      <webElementGuid>028dbdc3-0fd1-4df0-9925-5fa19358609a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
