<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio7_radio8</name>
   <tag></tag>
   <elementGuidId>23485d40-bf10-4b1d-a113-00ad85230c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>863d0651-2bd5-4672-9cea-170b05a4429e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3623ea22-02f7-457c-a453-41609d766bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio8</value>
      <webElementGuid>961a8d0e-7fdb-46aa-bb11-d68b0ac30350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio8</value>
      <webElementGuid>88d01e10-c0e6-457c-b9ae-f9fe9772df15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio8&quot;)</value>
      <webElementGuid>e0283a29-5ed2-4d96-9c5d-ef16415a2dc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio8']</value>
      <webElementGuid>8048e2cb-3c9d-4edf-864e-771bd60e20f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[28]</value>
      <webElementGuid>ce666e68-3d95-4eca-8b3f-52a011e2280a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio8']</value>
      <webElementGuid>411a2301-855d-4310-96b0-0e54e5a047dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
