<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text3_text3</name>
   <tag></tag>
   <elementGuidId>4aefa935-2558-4665-aeeb-74fb7f1af419</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#text3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52339d00-55d2-4b78-a95c-be460c2a5755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d04932ee-2136-456e-ad34-f8281cb90619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text3</value>
      <webElementGuid>4157d523-4a31-4bf4-be68-822974896d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text3&quot;)</value>
      <webElementGuid>63f734a7-ac89-4294-a475-4f3a7fc5e9a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text3']</value>
      <webElementGuid>319531a8-c843-46e2-bd31-1d89ef299878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>b6785497-be90-4faa-a939-ce0c7c82cfa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text3']</value>
      <webElementGuid>4e8a543f-72ca-495c-a65b-4d7b1c55518e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
