<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio5_radio6</name>
   <tag></tag>
   <elementGuidId>09e16af8-ce0e-4545-abf3-91f7e77fe8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff24f555-0bc3-49c6-8b97-73719c559885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e11e5895-7081-46b2-8abb-baae349c6ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio6</value>
      <webElementGuid>bfd5653a-5cc6-43d2-a580-936318d09527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio6</value>
      <webElementGuid>527dd26f-726e-4759-b1ac-fb9b35edf706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio6&quot;)</value>
      <webElementGuid>1cc84f48-4216-4a16-9f01-6af7e06393cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio6']</value>
      <webElementGuid>d2261201-0b0e-400d-9012-220dff0710f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[26]</value>
      <webElementGuid>4f1b74d7-e057-4d3b-8ffc-96743687fda8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio6']</value>
      <webElementGuid>08e7caa4-7339-419c-8c00-2c6d792c1871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
