<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio1_radio2</name>
   <tag></tag>
   <elementGuidId>9a31aa5e-6651-489f-b7a6-f5c95b53f287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f1d06bb-b884-4b3f-b759-d7309d0d20cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>885b1852-5654-4bc9-8e30-9d1888bb0a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio2</value>
      <webElementGuid>b902ca75-71fa-410b-82de-06bb7936f5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio2</value>
      <webElementGuid>81507d0f-8d0d-4f39-8254-6dd06952bc90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio2&quot;)</value>
      <webElementGuid>8d25edab-ddcd-4141-8b21-29ab379cd086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio2']</value>
      <webElementGuid>4061eb5b-f4ad-43a0-85c4-8f1fb344c272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[22]</value>
      <webElementGuid>80ee71a7-764c-418e-986e-f1413129e178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio2']</value>
      <webElementGuid>704e0ce0-5f3b-472c-bff6-46eb12d41cd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
