<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_value1          value2          valu_9f7bd8_1</name>
   <tag></tag>
   <elementGuidId>27c63a49-5004-4f99-9ce5-ee4a268cb8b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='option6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0ca0c44d-5b3a-444d-80ee-67107d97224b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option6</value>
      <webElementGuid>77267a39-f008-4f7f-83b6-3812a2e85878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          value1
          value2
          value3
          value4
        </value>
      <webElementGuid>c3ff7d5d-6e95-4056-b3b4-f2727caafecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option6&quot;)</value>
      <webElementGuid>734378eb-2488-44ba-8bb0-00a024249e9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='option6']</value>
      <webElementGuid>140c5924-f171-4372-a08c-199e679544e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option6:'])[1]/following::select[1]</value>
      <webElementGuid>dcacf23f-99ee-4340-98e5-d5c9a665e253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option5:'])[1]/following::select[2]</value>
      <webElementGuid>249b2651-3a52-4e47-b753-33784dd30c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option7:'])[1]/preceding::select[1]</value>
      <webElementGuid>a4021e22-ba19-40a6-bb0f-a38ec99f6233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a option8:'])[1]/preceding::select[2]</value>
      <webElementGuid>d762d069-c2fb-4e1d-a5fc-562d5b3b2d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[6]</value>
      <webElementGuid>8825ea78-0298-410e-94e1-85280c4b3f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'option6' and (text() = '
          value1
          value2
          value3
          value4
        ' or . = '
          value1
          value2
          value3
          value4
        ')]</value>
      <webElementGuid>9dc3d2b3-188a-4a42-b2ca-973e1a90e4b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
